version: "3"
services:
  odoo:
    image: kobros-tech/odoo:17.0
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "0.0.0.0:8069:8069"
    volumes:
      - data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  postgres:
    image: kobros-tech/postgres:15
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data/pgdata

volumes:
  data:
  db:
